//
// Created by ICR on 28.03.2024.
//

#ifndef VORLESUNG2_WORKWITHINHERITANCEANDVIRTUALMETHODS_H
#define VORLESUNG2_WORKWITHINHERITANCEANDVIRTUALMETHODS_H

void workWithInheritanceAndVirtualMethods();

#endif //VORLESUNG2_WORKWITHINHERITANCEANDVIRTUALMETHODS_H
